### ISSUE TITLE
[02-space_stretching.ipynb] Color pattern for show_scatterplot

### ISSUE THREAD

**Issue by aeryskyB** [Atcold/NYU-DLSP20#847]
*Hi!*

I saw your lecture and came here expecting the updated colors.  
But, it was not updated.  
So, I tried tweaking things on my own.  
However, the result turned out a little bit weird!
![image](https://github.com/Atcold/NYU-DLSP20/assets/79935164/8e143580-d93c-4e5c-a217-0d17ec924d55)  
It doesn't look the same. TT  
  
Is there any possibility for future updates?
Or should I make a PR?  
  
*Best!*

**Comment by Atcold** [comment]
Haha, you're right. I should push an update (which is way overdue).
I made it work by querying the colour from this scheme.
![ziegler](https://github.com/Atcold/NYU-DLSP20/assets/2119355/68c150ef-8274-4972-96e4-8c09dda16a0c)

**Comment by aeryskyB** [comment]
Thanks for sharing the coloring scheme, and the *update*...
  
Best wishes...^^

**Comment by Atcold** [comment]
Students asked me to do this for the last 8 semesters 🥲
You're welcome. Thanks for opening the issue.
